Repository pytrip/pytripgui, pull requests merged in 2021-08, with the labels that each got.

#420 Refactor canvas vc
  pytripgui/canvas_vc/canvas_controller.py
  pytripgui/canvas_vc/canvas_plotter.py
  pytripgui/canvas_vc/canvas_view.py
  pytripgui/canvas_vc/plotter/__init__.py
  pytripgui/canvas_vc/plotter/bars/__init__.py
  pytripgui/canvas_vc/plotter/bars/bar_base.py
  pytripgui/canvas_vc/plotter/bars/ctx_bar.py
  pytripgui/canvas_vc/plotter/bars/dos_bar.py
  pytripgui/canvas_vc/plotter/bars/let_bar.py
  pytripgui/canvas_vc/plotter/bars/projection_enum.py
  pytripgui/canvas_vc/plotter/coordinate_info.py
  pytripgui/canvas_vc/plotter/images/__init__.py
  pytripgui/canvas_vc/plotter/images/ctx_image.py
  pytripgui/canvas_vc/plotter/images/dose_image.py
  pytripgui/canvas_vc/plotter/images/let_image.py
  pytripgui/canvas_vc/plotter/images/patient_image_base.py
  pytripgui/canvas_vc/plotter/managers/__init__.py
  pytripgui/canvas_vc/plotter/managers/blit_manager.py
  pytripgui/canvas_vc/plotter/managers/placement_manager.py
  pytripgui/canvas_vc/plotter/managers/plotting_manager.py
  pytripgui/canvas_vc/plotter/mpl_plotter.py
Labels: ready

#432 Fix for package upload
  .github/workflows/test.yml
  appveyor.yml
Labels: in progress

#434 adding python 3.9 to setup.py and some cleaning
  .travis/check_package_deploy.sh
  CONTRIBUTING.rst
  MANIFEST.in
  README.rst
  docs/technical.rst
  setup.py
  tox.ini
Labels: ready

#449 About button fix
  pytripgui/main.py
Labels: bug

#446 Load patients without VOI
  pytripgui/app_logic/app_callbacks.py
  pytripgui/canvas_vc/canvas_controller.py
  pytripgui/canvas_vc/canvas_view.py
Labels: enhancement

#424 Feature/372 Export CT cube
  pytripgui/app_logic/app_callbacks.py
  pytripgui/app_logic/patient_tree.py
  pytripgui/main_window_qt_vc/main_window_view.py
  pytripgui/plan_executor/patient_model.py
  pytripgui/tree_vc/tree_controller.py
  pytripgui/tree_vc/tree_view.py
Labels: enhancement

#362 Feature/358 add empty patient; general small fixes
  pytripgui/app_logic/app_callbacks.py
  pytripgui/canvas_vc/projection_selector.py
  pytripgui/empty_patient_vc/__init__.py
  pytripgui/empty_patient_vc/empty_patient_cont.py
  pytripgui/empty_patient_vc/empty_patient_view.py
  pytripgui/view/add_patient.ui
  pytripgui/view/empty_patient.ui
  pytripgui/view/qt_gui.py
  pytripgui/view/qt_view_adapter.py
  pytripgui/view/trip_config.ui
Labels: in progress

#437 Fix plotting VOIs
  pytripgui/canvas_vc/canvas_controller.py
  pytripgui/canvas_vc/canvas_view.py
  pytripgui/canvas_vc/objects/vdx.py
  pytripgui/canvas_vc/plot_model.py
  pytripgui/canvas_vc/plotter/managers/plotting_manager.py
  pytripgui/canvas_vc/plotter/managers/voi_manager.py
  pytripgui/canvas_vc/plotter/mpl_plotter.py
  pytripgui/canvas_vc/projection_selector.py
Labels: ready

#457 Coordinate info enhancements
  pytripgui/canvas_vc/plotter/coordinate_info.py
Labels: ready

#472 VOI colors matching pytrip
  pytripgui/canvas_vc/plotter/managers/voi_manager.py
  requirements.txt
  setup.py
Labels: ready
